---
- name: gather facts for web group
  hosts: web
  gather_facts: true
- name: haproxy
  hosts: lb
  become: true
  tasks:
    - name: install haproxy
      apt:
        name: haproxy
        state: present
        update_cache: true
    - name: start & enable haproxy
      service:
        name: haproxy
        state: started
        enabled: yes
    - name: template out haproxy config
      template:
        src: templates/haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
        mode: 0640
        owner: root
        group: root
      notify: restart haproxy
    - name: allow SSH traffic
      iptables:
        chain: INPUT
        destination_port: 80
        jump: ACCEPT
        protocol: tcp
  handlers:
    - name: restart haproxy
      service:
        name: haproxy
        state: restarted