---
- name: first play
  hosts: web
  gather_facts: false
  vars_prompt:
  - name: "version"
    prompt: "which version do you want to install?"
  tasks:
    - name : debug task
      debug:
       msg: "will install apache -{{version}}"
    - name: 
      apt:
        name: "apache{{version}}"
        state: present