---
- name: web servers
  hosts: web
  become: true
  tasks:
    - name: install apache
      apt:
        name: apache2,git
        state: latest
        update_cache: true
      tags:
        - base
    - name: install packages
      apt:
        name: 
          - php
          - php-mysql
        state: present
        update_cache: true
      notify: restart apache2
      tags:
        - base
    - name: start apache service
      service: 
        name: apache2
        state: started
        enabled: yes
      tags:
        - base
    - name: deploy index.php
      git:
        repo: "{{ repository }}"
        dest: "{{ document_root_path }}"
      tags:
        - content
    - name: vhost config block
      block:
      - name: Copy vhost config
        copy:
          src: files/ansible_site.conf
          dest: "{{ vhost_config_file }}"
          owner: root
          group: root
          mode: 0644
        notify: restart apache2
      - name: check configuration validity
        command: service apache2 status
      rescue:
      - name: remove bad virtual host configuration
        file:
          path: "{{ vhost_config_file }}"
          state: absent
      - name: Rolling back - ending playbook
        fail:
          msg: "Configuration file is not valid. Please check that before re-running the playbook"
      tags:
        - vhost
    - name: Configure apache2.conf
      lineinfile:
        path: "{{ apache_config_file }}"
        regexp: "^IncludeOptional"
        line: "IncludeOptional conf-enabled/*.conf"
      notify: restart apache2
      tags:
        - vhost
    - name: install hello world script with db
      copy:
        src: files/db.php
        dest: "{{ document_root_path }}db.php"
        mode: 0775
      tags:
        - content
    - name: allow SSH traffic
      iptables:
        chain: INPUT
        destination_port: 80
        jump: ACCEPT
        protocol: tcp
      tags:
        - security
        - firewall
  handlers:
    - name: restart apache2
      service:
        name: apache2
        state: restarted